println("=" ^ 60)
println("  AI Career Copilot")
println("  Author  : Ramrup Satpati (RSNPIIT) · IIT Madras")
println("  License : GPL-3.0")
println("=" ^ 60)

println()
println("  ABOUT")
println("  ─────")
println("  An intelligent assistant to help users navigate their")
println("  career journey — resume building, job matching,")
println("  interview prep, and skill gap analysis.")

println()
println("  FEATURES")
println("  ────────")
println("  → Resume analysis and feedback")
println("  → Job description matching and scoring")
println("  → Skill gap identification")
println("  → Interview question generation")
println("  → Career path suggestions")

println()
println("  STACK")
println("  ─────")
println("  → Python 3.10+")
println("  → LLM API (OpenAI / Anthropic / Gemini)")
println("  → Flask (web interface)")
println("  → Linux · VSCodium")

println()
println("  USAGE")
println("  ─────")
println("  \$ source venv/bin/activate")
println("  \$ pip install -r requirements.txt")
println("  \$ python3 run.py")

println()
println("=" ^ 60)
